# This workflow will build and push files to Amazon S3 bucket.
# To use this workflow, you will need to complete the following set-up steps:
# 1. Setup S3 bucket
#    Replace the value of the `BUCKET_NAME` environment variable in the workflow below with your S3 bucket name.
#    Replace the value of the `AWS_REGION` environment variable in the workflow below with your S3 bucket's region.
# 2. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.
# 3. Store an fontawasome auth token in GitHub Actions secrets named `FONTAWASOME_AUTH_TOKEN`.

name: Deploy to Amazon S3 staging bucket

# Triggered on commits to the staging branch.
on:
  push:
    branches:
      - 'staging'

env:
  AWS_REGION: us-east-1                                        # set this to your preferred AWS region, e.g. us-west-1

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependences
        run: |
          npm i

      - name: Build docker image
        run: |
          npm i